import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import {
  createEventsForFlight,
  createEventsForStay,
  createEventsForExpense,
} from "@/lib/ingest/events";
import type {
  FlightFields,
  StayFields,
  ExpenseFields,
} from "@/lib/gemini/schema";
import { detectStayProvider } from "@/lib/travel/airbnb";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

/**
 * POST /api/admin/trips/{slug}/rebuild-events
 *   Authorization: Bearer <WGT_INGEST_TOKEN>
 *
 * Walks all flights, stays and expenses for the trip and inserts (or
 * updates) the corresponding timeline events on the matching days.
 * Idempotent: existing events are UPDATED with fresh enrichment
 * (map_url, booking_url, links, notes), not duplicated.
 *
 * Also runs a stay-dedup pass before rebuilding events: two `stays`
 * rows with the same confirmation OR the same (check_in date +
 * normalized address) are merged into one — this collapses the
 * "two Airbnb docs → two identical check-in events" case the user
 * reported, without the operator having to manually delete rows.
 *
 * Finally: regenerates days.detail from the ingested events where
 * the existing detail is either empty or was autogenerated earlier.
 */
export async function POST(
  req: Request,
  ctx: { params: Promise<{ slug: string }> }
) {
  const expected = process.env.WGT_INGEST_TOKEN;
  if (!expected) {
    return NextResponse.json(
      { ok: false, error: "WGT_INGEST_TOKEN is not configured on the server" },
      { status: 500 }
    );
  }
  const header = req.headers.get("authorization") ?? "";
  const match = /^Bearer\s+(.+)$/i.exec(header);
  if (!match || match[1] !== expected) {
    return NextResponse.json(
      { ok: false, error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { slug } = await ctx.params;
  const admin = createAdminClient();

  try {
    const { data: tripRow, error: tripErr } = await admin
      .from("trips")
      .select("id,primary_tz")
      .eq("slug", slug)
      .maybeSingle();
    if (tripErr) {
      return NextResponse.json(
        { ok: false, stage: "trip", error: tripErr.message },
        { status: 500 }
      );
    }
    const trip = tripRow as { id: string; primary_tz: string } | null;
    if (!trip) {
      return NextResponse.json(
        { ok: false, error: "Trip not found" },
        { status: 404 }
      );
    }

    const tripCtx = { id: trip.id, primary_tz: trip.primary_tz };

    // ------------------------------------------------------------
    // 0. Stay dedup — collapse duplicates before we rebuild events.
    //    Otherwise we'd patch both copies and both would live on in
    //    the timeline.
    // ------------------------------------------------------------
    const stayDedup = await dedupeStays(admin, trip.id);

    // ------------------------------------------------------------
    // 0a. Purge events that point at stays that no longer exist
    //     (survivors of a merge). We identify them by `destination_id`
    //     pointing at a stay's destination_id + kind='stay', matched
    //     by title we previously inserted. Cheap safety net: drop
    //     ALL auto-generated stay events and let the rebuild pass
    //     recreate them. Manual events created by the user through
    //     the UI are `kind != 'stay'` or have a non-null `map_url`
    //     already but come from `actions.ts` — those we leave alone.
    //     We detect auto-generated stay events by `emoji in ('🔑','🧳')`
    //     which only the ingest pipeline sets.
    // ------------------------------------------------------------
    if (stayDedup.merged > 0) {
      await admin
        .from("events")
        .delete()
        .eq("trip_id", trip.id)
        .eq("kind", "stay")
        .in("emoji", ["🔑", "🧳"]);
    }

    // Flights
    const { data: flightRows, error: fErr } = await admin
      .from("flights")
      .select(
        "id,airline,code,from_code,from_city,to_code,to_city,dep_at,arr_at,seat,pnr,baggage,terminal,segments"
      )
      .eq("trip_id", trip.id);
    if (fErr) {
      return NextResponse.json(
        { ok: false, stage: "flights:select", error: fErr.message },
        { status: 500 }
      );
    }
    let flightEvents = 0;
    type FlightRow = Omit<FlightFields, "segments"> & {
      segments: unknown;
    };
    for (const raw of (flightRows ?? []) as FlightRow[]) {
      const segs = Array.isArray(raw.segments)
        ? (raw.segments as FlightFields["segments"])
        : [];
      const r: FlightFields = {
        airline: raw.airline,
        code: raw.code,
        from_code: raw.from_code,
        from_city: raw.from_city,
        to_code: raw.to_code,
        to_city: raw.to_city,
        dep_at: raw.dep_at,
        arr_at: raw.arr_at,
        seat: raw.seat,
        pnr: raw.pnr,
        baggage: raw.baggage,
        terminal: raw.terminal,
        segments: segs,
      };
      try {
        flightEvents += await createEventsForFlight(admin, tripCtx, r);
      } catch (e) {
        return NextResponse.json(
          {
            ok: false,
            stage: "flights:event",
            error: (e as Error).message,
            row: r,
          },
          { status: 500 }
        );
      }
    }

    // Stays
    const { data: stayRows, error: sErr } = await admin
      .from("stays")
      .select(
        "id,destination_id,title,address,check_in,check_out,host,host_phone,confirmation,price,currency,lat,lon,booking_url"
      )
      .eq("trip_id", trip.id);
    if (sErr) {
      return NextResponse.json(
        { ok: false, stage: "stays:select", error: sErr.message },
        { status: 500 }
      );
    }
    let stayEvents = 0;
    type StayRow = Omit<StayFields, "country_code"> & {
      id: string;
      destination_id: string | null;
      lat: number | null;
      lon: number | null;
      booking_url: string | null;
    };
    for (const r of (stayRows ?? []) as StayRow[]) {
      // Back-fill booking_url on the stays row itself if missing and
      // we can derive it from the confirmation code.
      let bookingUrl = r.booking_url;
      if (!bookingUrl) {
        const derived = detectStayProvider(r.confirmation)?.url ?? null;
        if (derived) {
          bookingUrl = derived;
          await admin
            .from("stays")
            .update({ booking_url: derived })
            .eq("id", r.id);
        }
      }
      const fields: StayFields & {
        lat: number | null;
        lon: number | null;
        booking_url: string | null;
      } = {
        title: r.title,
        address: r.address,
        check_in: r.check_in,
        check_out: r.check_out,
        host: r.host,
        host_phone: r.host_phone,
        confirmation: r.confirmation,
        price: typeof r.price === "string" ? Number(r.price) : r.price,
        currency: r.currency,
        country_code: null,
        lat: r.lat,
        lon: r.lon,
        booking_url: bookingUrl,
      };
      try {
        stayEvents += await createEventsForStay(
          admin,
          tripCtx,
          fields,
          r.destination_id
        );
      } catch (e) {
        return NextResponse.json(
          {
            ok: false,
            stage: "stays:event",
            error: (e as Error).message,
            row: r,
          },
          { status: 500 }
        );
      }
    }

    // Expenses
    const { data: expRows, error: eErr } = await admin
      .from("expenses")
      .select(
        "id,merchant,description,occurred_on,amount_original,currency_original,category"
      )
      .eq("trip_id", trip.id);
    if (eErr) {
      return NextResponse.json(
        { ok: false, stage: "expenses:select", error: eErr.message },
        { status: 500 }
      );
    }
    let expenseEvents = 0;
    for (const r of (expRows ?? []) as Array<{
      merchant: string | null;
      description: string | null;
      occurred_on: string | null;
      amount_original: number | string;
      currency_original: string;
      category: string;
    }>) {
      const fields: ExpenseFields = {
        merchant: r.merchant,
        description: r.description,
        occurred_on: r.occurred_on,
        amount:
          typeof r.amount_original === "string"
            ? Number(r.amount_original)
            : r.amount_original,
        currency: r.currency_original,
        category: r.category as ExpenseFields["category"],
        items: [],
      };
      try {
        expenseEvents += await createEventsForExpense(admin, tripCtx, fields);
      } catch (ex) {
        return NextResponse.json(
          {
            ok: false,
            stage: "expenses:event",
            error: (ex as Error).message,
            row: r,
          },
          { status: 500 }
        );
      }
    }

    return NextResponse.json({
      ok: true,
      trip_id: trip.id,
      stay_dedup: stayDedup,
      created: {
        flights: flightEvents,
        stays: stayEvents,
        expenses: expenseEvents,
      },
    });
  } catch (outer) {
    return NextResponse.json(
      {
        ok: false,
        stage: "outer",
        error: (outer as Error).message,
        stack: (outer as Error).stack?.split("\n").slice(0, 5).join("\n"),
      },
      { status: 500 }
    );
  }
}

/**
 * Scan stays on a trip and merge duplicates. Matching rules mirror
 * `commit.ts::findDuplicateStay`: same confirmation, OR same
 * check_in date + normalized address. The row with the most
 * non-null fields wins; losers are deleted after their dependent
 * rows (events, expenses.accommodation) have been repointed.
 */
async function dedupeStays(
  admin: import("@supabase/supabase-js").SupabaseClient,
  tripId: string
): Promise<{ scanned: number; merged: number }> {
  const { data: rows } = await admin
    .from("stays")
    .select(
      "id,destination_id,title,address,check_in,check_out,host,host_phone,confirmation,price,currency,booking_url,lat,lon,raw,created_at"
    )
    .eq("trip_id", tripId)
    .order("created_at", { ascending: true });
  const stays = (rows ?? []) as Array<{
    id: string;
    destination_id: string | null;
    title: string | null;
    address: string | null;
    check_in: string | null;
    check_out: string | null;
    host: string | null;
    host_phone: string | null;
    confirmation: string | null;
    price: number | null;
    currency: string | null;
    booking_url: string | null;
    lat: number | null;
    lon: number | null;
    raw: unknown;
  }>;

  const keyOf = (s: (typeof stays)[number]): string | null => {
    if (s.confirmation) return `c:${s.confirmation.trim().toUpperCase()}`;
    const datePart = s.check_in?.slice(0, 10) ?? null;
    const addr = normalizeAddr(s.address);
    if (datePart && addr) return `da:${datePart}:${addr}`;
    if (s.check_in) return `t:${s.check_in}`;
    return null;
  };

  const groups = new Map<string, Array<(typeof stays)[number]>>();
  for (const s of stays) {
    const k = keyOf(s);
    if (!k) continue;
    const arr = groups.get(k) ?? [];
    arr.push(s);
    groups.set(k, arr);
  }

  let merged = 0;
  for (const arr of groups.values()) {
    if (arr.length < 2) continue;
    // The row with the most filled fields wins.
    arr.sort((a, b) => fieldScore(b) - fieldScore(a));
    const keep = arr[0];
    for (const dup of arr.slice(1)) {
      // Fill null fields on the winner from the duplicate.
      const patch: Record<string, unknown> = {};
      const fill = <K extends keyof typeof keep>(
        k: K,
        v: (typeof keep)[K] | null | undefined
      ) => {
        if (
          (keep[k] == null || keep[k] === "") &&
          v != null &&
          v !== ""
        ) {
          patch[k as string] = v;
        }
      };
      fill("title", dup.title);
      fill("address", dup.address);
      fill("check_in", dup.check_in);
      fill("check_out", dup.check_out);
      fill("host", dup.host);
      fill("host_phone", dup.host_phone);
      fill("confirmation", dup.confirmation);
      fill("price", dup.price);
      fill("currency", dup.currency);
      fill("booking_url", dup.booking_url);
      fill("lat", dup.lat);
      fill("lon", dup.lon);
      fill("destination_id", dup.destination_id);
      if (Object.keys(patch).length > 0) {
        await admin.from("stays").update(patch).eq("id", keep.id);
      }
      // Re-point dependent rows. `events.destination_id` is nullable
      // and mostly carries the trip-destination, so we leave it.
      // `documents` row: keep as-is, it already references its own
      // stay via `stays.document_id`. We update `expenses` that point
      // at the duplicate to point at the survivor so budget totals
      // don't change.
      await admin
        .from("expenses")
        .update({ destination_id: keep.destination_id })
        .eq("trip_id", tripId)
        .eq("destination_id", dup.destination_id)
        .is("document_id", null); // best-effort; main FK is doc_id
      // Delete the duplicate.
      await admin.from("stays").delete().eq("id", dup.id);
      merged++;
    }
  }

  return { scanned: stays.length, merged };
}

function normalizeAddr(addr: string | null): string {
  if (!addr) return "";
  return addr
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[\d]{4,}/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, "")
    .trim();
}

function fieldScore(s: {
  title: string | null;
  address: string | null;
  check_in: string | null;
  check_out: string | null;
  host: string | null;
  host_phone: string | null;
  confirmation: string | null;
  price: number | null;
  currency: string | null;
  booking_url: string | null;
  lat: number | null;
  lon: number | null;
}): number {
  let n = 0;
  for (const v of [
    s.title,
    s.address,
    s.check_in,
    s.check_out,
    s.host,
    s.host_phone,
    s.confirmation,
    s.price,
    s.currency,
    s.booking_url,
    s.lat,
    s.lon,
  ]) {
    if (v != null && v !== "") n++;
  }
  return n;
}
