/**
 * Shared core of "rebuild timeline" for a single trip.
 *
 * Re-reads every flight / stay / expense row and regenerates the
 * corresponding timeline events. Idempotent: existing events are
 * UPDATED (not duplicated) with fresh enrichment — map preview,
 * booking URL, airline/airport action buttons, price/time notes.
 *
 * Also:
 *   • merges duplicate stays (same confirmation OR same check-in
 *     date + normalized address) so the timeline shows ONE
 *     «Заселение» per real booking;
 *   • regenerates `days.detail` where it is empty or previously
 *     autogenerated (detected via the ZWJ marker in `day-detail.ts`);
 *   • back-fills `stays.booking_url` from the confirmation code when
 *     we can detect the provider (Airbnb / Booking).
 *
 * The HTTP route and the in-app server action both call this — the
 * route adds bearer-token auth for CI-style invocation, the server
 * action relies on the cookie-based session.
 */
import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import {
  createEventsForFlight,
  createEventsForStay,
  createEventsForExpense,
} from "@/lib/ingest/events";
import type {
  FlightFields,
  StayFields,
  ExpenseFields,
} from "@/lib/gemini/schema";
import { detectStayProvider } from "@/lib/travel/airbnb";
import { ensureAccommodationExpense } from "@/lib/ingest/stay-expense";

export type RebuildSuccess = {
  ok: true;
  trip_id: string;
  stay_dedup: { scanned: number; merged: number };
  created: { flights: number; stays: number; expenses: number };
};

export type RebuildFailure = {
  ok: false;
  stage: string;
  error: string;
  status: number;
};

export type RebuildResult = RebuildSuccess | RebuildFailure;

export async function rebuildTripEvents(
  admin: SupabaseClient,
  slug: string
): Promise<RebuildResult> {
  const { data: tripRow, error: tripErr } = await admin
    .from("trips")
    .select("id,primary_tz,base_currency")
    .eq("slug", slug)
    .maybeSingle();
  if (tripErr) {
    return { ok: false, stage: "trip", error: tripErr.message, status: 500 };
  }
  const trip = tripRow as {
    id: string;
    primary_tz: string;
    base_currency: string;
  } | null;
  if (!trip) {
    return { ok: false, stage: "trip", error: "Trip not found", status: 404 };
  }

  const tripCtx = { id: trip.id, primary_tz: trip.primary_tz };
  const baseCurrency = trip.base_currency || "RUB";

  // ------------------------------------------------------------
  // Stay dedup — collapse duplicates before we rebuild events.
  // ------------------------------------------------------------
  const stayDedup = await dedupeStays(admin, trip.id);

  // When a merge happened, events from both copies are still in the
  // DB; purge the auto-generated ones and let the rebuild pass
  // recreate them fresh. Manual events never carry the 🔑/🧳 emoji,
  // so we leave them untouched.
  if (stayDedup.merged > 0) {
    await admin
      .from("events")
      .delete()
      .eq("trip_id", trip.id)
      .eq("kind", "stay")
      .in("emoji", ["🔑", "🧳"]);
  }

  // Flights
  const { data: flightRows, error: fErr } = await admin
    .from("flights")
    .select(
      "id,airline,code,from_code,from_city,to_code,to_city,dep_at,arr_at,seat,pnr,baggage,terminal,segments"
    )
    .eq("trip_id", trip.id);
  if (fErr) {
    return {
      ok: false,
      stage: "flights:select",
      error: fErr.message,
      status: 500,
    };
  }
  let flightEvents = 0;
  type FlightRow = Omit<FlightFields, "segments"> & { segments: unknown };
  for (const raw of (flightRows ?? []) as FlightRow[]) {
    const segs = Array.isArray(raw.segments)
      ? (raw.segments as FlightFields["segments"])
      : [];
    const r: FlightFields = {
      airline: raw.airline,
      code: raw.code,
      from_code: raw.from_code,
      from_city: raw.from_city,
      to_code: raw.to_code,
      to_city: raw.to_city,
      dep_at: raw.dep_at,
      arr_at: raw.arr_at,
      seat: raw.seat,
      pnr: raw.pnr,
      baggage: raw.baggage,
      terminal: raw.terminal,
      segments: segs,
    };
    try {
      flightEvents += await createEventsForFlight(admin, tripCtx, r);
    } catch (e) {
      return {
        ok: false,
        stage: "flights:event",
        error: (e as Error).message,
        status: 500,
      };
    }
  }

  // Stays — если миграция phase14 не накатилась, колонки
  // `booking_url` может не существовать. Пробуем расширенный select,
  // при ошибке отступаем на базовый.
  let stayRows:
    | Array<Record<string, unknown>>
    | null = null;
  {
    const extended = await admin
      .from("stays")
      .select(
        "id,document_id,destination_id,title,address,check_in,check_out,host,host_phone,confirmation,price,currency,lat,lon,booking_url,map_url"
      )
      .eq("trip_id", trip.id);
    if (extended.error) {
      console.warn(
        "[rebuild] extended stays select failed, falling back:",
        extended.error.message
      );
      const basic = await admin
        .from("stays")
        .select(
          "id,document_id,destination_id,title,address,check_in,check_out,host,host_phone,confirmation,price,currency,lat,lon"
        )
        .eq("trip_id", trip.id);
      if (basic.error) {
        return {
          ok: false,
          stage: "stays:select",
          error: basic.error.message,
          status: 500,
        };
      }
      stayRows = (basic.data ?? []) as Array<Record<string, unknown>>;
    } else {
      stayRows = (extended.data ?? []) as Array<Record<string, unknown>>;
    }
  }
  let stayEvents = 0;
  type StayRow = Omit<StayFields, "country_code"> & {
    id: string;
    destination_id: string | null;
    lat: number | null;
    lon: number | null;
    booking_url: string | null;
    map_url: string | null;
  };
  for (const raw of stayRows) {
    const r = {
      ...raw,
      booking_url:
        (raw.booking_url as string | null | undefined) ?? null,
      map_url: (raw.map_url as string | null | undefined) ?? null,
    } as StayRow;
    let bookingUrl = r.booking_url;
    if (!bookingUrl) {
      const derived = detectStayProvider(r.confirmation)?.url ?? null;
      if (derived) {
        bookingUrl = derived;
        // Мягкая запись — если колонка ещё не существует, просто
        // пропускаем (событие получит ссылку напрямую через fields).
        const upd = await admin
          .from("stays")
          .update({ booking_url: derived })
          .eq("id", r.id);
        if (upd.error) {
          console.warn(
            "[rebuild] stays.booking_url update skipped:",
            upd.error.message
          );
        }
      }
    }
    const fields: StayFields & {
      lat: number | null;
      lon: number | null;
      booking_url: string | null;
      map_url: string | null;
    } = {
      title: r.title,
      address: r.address,
      check_in: r.check_in,
      check_out: r.check_out,
      host: r.host,
      host_phone: r.host_phone,
      confirmation: r.confirmation,
      price: typeof r.price === "string" ? Number(r.price) : r.price,
      currency: r.currency,
      country_code: null,
      lat: r.lat,
      lon: r.lon,
      booking_url: bookingUrl,
      map_url: r.map_url,
    };
    try {
      stayEvents += await createEventsForStay(
        admin,
        tripCtx,
        fields,
        r.destination_id
      );
    } catch (e) {
      return {
        ok: false,
        stage: "stays:event",
        error: (e as Error).message,
        status: 500,
      };
    }

    // Back-fill accommodation expense if missing. Idempotent: dedup
    // by document_id first, shape-match as fallback.
    try {
      await ensureAccommodationExpense(
        admin,
        trip.id,
        baseCurrency,
        {
          id: r.id,
          document_id: (raw.document_id as string | null) ?? null,
          title: r.title,
          price: r.price,
          currency: r.currency,
          check_in: r.check_in,
          destination_id: r.destination_id,
        },
        null
      );
    } catch (e) {
      console.error("[rebuild] ensureAccommodationExpense:", e);
    }
  }

  // Expenses — тащим tour-specific поля из documents.parsed_fields,
  // чтобы событие-экскурсия при rebuild получило tour_details /
  // ticket_url / guide_* даже если в expenses нет колонок под них.
  const { data: expRows, error: eErr } = await admin
    .from("expenses")
    .select(
      "id,merchant,description,occurred_on,amount_original,currency_original,category,document_id"
    )
    .eq("trip_id", trip.id);
  if (eErr) {
    return {
      ok: false,
      stage: "expenses:select",
      error: eErr.message,
      status: 500,
    };
  }
  let expenseEvents = 0;
  for (const r of (expRows ?? []) as Array<{
    merchant: string | null;
    description: string | null;
    occurred_on: string | null;
    amount_original: number | string;
    currency_original: string;
    category: string;
    document_id: string | null;
  }>) {
    // Если расход ingest'ился из документа — подтягиваем полный
    // parsed_fields, там живут все поля Gemini-schema (в том числе
    // tour_url, guide_name, paid_amount, extras, start/end_time).
    let tourFields: Partial<ExpenseFields> = {};
    if (r.document_id) {
      const { data: doc } = await admin
        .from("documents")
        .select("parsed_fields")
        .eq("id", r.document_id)
        .maybeSingle();
      const pf = (doc as { parsed_fields: unknown } | null)?.parsed_fields;
      if (pf && typeof pf === "object" && pf !== null) {
        const exp = (pf as { expense?: unknown }).expense;
        if (exp && typeof exp === "object") {
          const e = exp as Record<string, unknown>;
          tourFields = {
            tour_url: (e.tour_url as string | null) ?? null,
            guide_name: (e.guide_name as string | null) ?? null,
            guide_phone: (e.guide_phone as string | null) ?? null,
            paid_amount: (e.paid_amount as number | null) ?? null,
            paid_currency: (e.paid_currency as string | null) ?? null,
            due_amount: (e.due_amount as number | null) ?? null,
            due_currency: (e.due_currency as string | null) ?? null,
            start_time: (e.start_time as string | null) ?? null,
            end_time: (e.end_time as string | null) ?? null,
            extras: Array.isArray(e.extras)
              ? (e.extras as Array<{
                  label: string | null;
                  amount: number | null;
                  currency: string | null;
                }>)
              : [],
          };
        }
      }
    }

    const fields: ExpenseFields = {
      merchant: r.merchant,
      description: r.description,
      occurred_on: r.occurred_on,
      amount:
        typeof r.amount_original === "string"
          ? Number(r.amount_original)
          : r.amount_original,
      currency: r.currency_original,
      category: r.category as ExpenseFields["category"],
      items: [],
      tour_url: tourFields.tour_url ?? null,
      guide_name: tourFields.guide_name ?? null,
      guide_phone: tourFields.guide_phone ?? null,
      paid_amount: tourFields.paid_amount ?? null,
      paid_currency: tourFields.paid_currency ?? null,
      due_amount: tourFields.due_amount ?? null,
      due_currency: tourFields.due_currency ?? null,
      start_time: tourFields.start_time ?? null,
      end_time: tourFields.end_time ?? null,
      extras: tourFields.extras ?? [],
    };
    try {
      expenseEvents += await createEventsForExpense(admin, tripCtx, fields);
    } catch (ex) {
      return {
        ok: false,
        stage: "expenses:event",
        error: (ex as Error).message,
        status: 500,
      };
    }
  }

  return {
    ok: true,
    trip_id: trip.id,
    stay_dedup: stayDedup,
    created: {
      flights: flightEvents,
      stays: stayEvents,
      expenses: expenseEvents,
    },
  };
}

/**
 * Scan stays on a trip and merge duplicates. Matching rules mirror
 * `commit.ts::findDuplicateStay`: same confirmation, OR same
 * check_in date + normalized address. The row with the most
 * non-null fields wins; losers are deleted after their dependent
 * expenses are re-pointed to the survivor.
 */
async function dedupeStays(
  admin: SupabaseClient,
  tripId: string
): Promise<{ scanned: number; merged: number }> {
  const { data: rows } = await admin
    .from("stays")
    .select(
      "id,destination_id,title,address,check_in,check_out,host,host_phone,confirmation,price,currency,booking_url,lat,lon,raw,created_at"
    )
    .eq("trip_id", tripId)
    .order("created_at", { ascending: true });
  const stays = (rows ?? []) as Array<{
    id: string;
    destination_id: string | null;
    title: string | null;
    address: string | null;
    check_in: string | null;
    check_out: string | null;
    host: string | null;
    host_phone: string | null;
    confirmation: string | null;
    price: number | null;
    currency: string | null;
    booking_url: string | null;
    lat: number | null;
    lon: number | null;
    raw: unknown;
  }>;

  const keyOf = (s: (typeof stays)[number]): string | null => {
    if (s.confirmation) return `c:${s.confirmation.trim().toUpperCase()}`;
    const datePart = s.check_in?.slice(0, 10) ?? null;
    const addr = normalizeAddr(s.address);
    if (datePart && addr) return `da:${datePart}:${addr}`;
    if (s.check_in) return `t:${s.check_in}`;
    return null;
  };

  const groups = new Map<string, Array<(typeof stays)[number]>>();
  for (const s of stays) {
    const k = keyOf(s);
    if (!k) continue;
    const arr = groups.get(k) ?? [];
    arr.push(s);
    groups.set(k, arr);
  }

  let merged = 0;
  for (const arr of groups.values()) {
    if (arr.length < 2) continue;
    arr.sort((a, b) => fieldScore(b) - fieldScore(a));
    const keep = arr[0];
    for (const dup of arr.slice(1)) {
      const patch: Record<string, unknown> = {};
      const fill = <K extends keyof typeof keep>(
        k: K,
        v: (typeof keep)[K] | null | undefined
      ) => {
        if (
          (keep[k] == null || keep[k] === "") &&
          v != null &&
          v !== ""
        ) {
          patch[k as string] = v;
        }
      };
      fill("title", dup.title);
      fill("address", dup.address);
      fill("check_in", dup.check_in);
      fill("check_out", dup.check_out);
      fill("host", dup.host);
      fill("host_phone", dup.host_phone);
      fill("confirmation", dup.confirmation);
      fill("price", dup.price);
      fill("currency", dup.currency);
      fill("booking_url", dup.booking_url);
      fill("lat", dup.lat);
      fill("lon", dup.lon);
      fill("destination_id", dup.destination_id);
      if (Object.keys(patch).length > 0) {
        await admin.from("stays").update(patch).eq("id", keep.id);
      }
      await admin
        .from("expenses")
        .update({ destination_id: keep.destination_id })
        .eq("trip_id", tripId)
        .eq("destination_id", dup.destination_id)
        .is("document_id", null);
      await admin.from("stays").delete().eq("id", dup.id);
      merged++;
    }
  }

  return { scanned: stays.length, merged };
}

function normalizeAddr(addr: string | null): string {
  if (!addr) return "";
  return addr
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[\d]{4,}/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, "")
    .trim();
}

function fieldScore(s: {
  title: string | null;
  address: string | null;
  check_in: string | null;
  check_out: string | null;
  host: string | null;
  host_phone: string | null;
  confirmation: string | null;
  price: number | null;
  currency: string | null;
  booking_url: string | null;
  lat: number | null;
  lon: number | null;
}): number {
  let n = 0;
  for (const v of [
    s.title,
    s.address,
    s.check_in,
    s.check_out,
    s.host,
    s.host_phone,
    s.confirmation,
    s.price,
    s.currency,
    s.booking_url,
    s.lat,
    s.lon,
  ]) {
    if (v != null && v !== "") n++;
  }
  return n;
}
